### ISSUE TITLE
Android Build Error

### ISSUE THREAD

**Issue by shamamit11** [floatinghotpot/cordova-plugin-flurry#13]
Hello
Whenever I try to build the Android app, in Error Console, It says it cannot copy Plugin.
I used:
Name: FlurryAdsPluginPro
Plugin ID: com.rjfun.cordova.flurryads
[x] Plugin is located in the Apache Cordova Plugins Registry

I am using Intel XDK for building App.

Also, the add is not showing. I copied the example file (text/index.html) and used my AD ID (from Flurry Site) but it is not working. Is there any thing I am missing to implement.
I am looking to get help on this.

Thanks in Advance !!

**Comment by shamamit11** [comment]
I used: com.flurry.sdk for the second time and I was able to build Android App but as I said it is not showing any ad.

**Comment by shamamit11** [comment]
![error1](https://cloud.githubusercontent.com/assets/10370106/5594908/0c180e42-928b-11e4-9470-d690d784fc12.PNG)

**Comment by floatinghotpot** [comment]
it's caused by duplicated sdk, as it's already included while having another one as dependent.

it's now fixed, please try again.

**Comment by shamamit11** [comment]
Ok, Many thanks :)
