### ISSUE TITLE
Error using Intel XDK build

### ISSUE THREAD

**Issue by matte5031** [floatinghotpot/cordova-plugin-flurry#34]
I'm going to explain a few steps incase it can help solving the problem.

I'm using Onesignal for push notification together with the intel xdk https://documentation.onesignal.com/docs/phonegap-sdk-installation#intel-xdk-click-to-expand

For this i use the plugin: https://github.com/one-signal/OneSignal-Cordova-SDK.git#PGB-Compat

**But** i also use theese two to together with the previous plugin:
 https://github.com/floatinghotpot/google-play-services
https://github.com/floatinghotpot/cordova-plugin-android-support-v4

**Then** when i try to build using this flurry plugin aswell i get the following error:
  Error: more than one library with package name 'com.google.android.gms'
  You can temporarily disable this error with android.enforceUniquePackageName=false
  However, this is temporary and will be enforced in 1.0

**So** what i did was that i removed the first additional onesignal plugin:
https://github.com/floatinghotpot/google-play-services
which got rid of the previous error aka "more than one "com.google.android.gms" package name"

**But** that gave me a new error which was:
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':dexRelease'.
com.android.ide.common.internal.LoggedErrorException: Failed to run command:
    .../android-sdk/build-tools/21.1.2/dx --dex --output .../Flurry/platforms/android/build/intermediates/dex/release --input-list=.../Flurry/platforms/android/build/intermediates/tmp/dex/release/inputList.txt
  Error Code:
    2
  Output:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
    at com.android.dx.command.dexer.Main.run(Main.java:246)
    at com.android.dx.command.dexer.Main.main(Main.java:215)
    at com.android.dx.command.Main.main(Main.java:106)
```
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 23.783 secs

.../Flurry/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: .../Flurry/platforms/android/gradlew with args: cdvBuildRelease,-b,.../Flurry/platforms/android/build.gradle,--no-daemon
Command finished with error code 1: .../Flurry/platforms/android/cordova/build --release
ERROR building one of the platforms: Error: .../Flurry/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: .../Flurry/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (.../cordova/cordova-cli/5.1.1/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Lastly** i removed the second additional onesignal plugin aswell which was:
https://github.com/floatinghotpot/cordova-plugin-android-support-v4

I was now able to build without any errors, however it seems like i cant use this flurry plugin and the required plugins for onesignal at the same time therefore i was wondering if there was any solutions for solving this problem.

Help is highly appreciated, thanks alot!

**Comment by matte5031** [comment]
I'm going to explain a few steps incase it can help solving the problem.

I'm using Onesignal for push notification together with the intel xdk https://documentation.onesignal.com/docs/phonegap-sdk-installation#intel-xdk-click-to-expand

For this i use the plugin: https://github.com/one-signal/OneSignal-Cordova-SDK.git#PGB-Compat

**But** i also use theese two to together with the previous plugin:
 https://github.com/floatinghotpot/google-play-services
https://github.com/floatinghotpot/cordova-plugin-android-support-v4

**Then** when i try to use this flurry plugin i get the following error:
  Error: more than one library with package name 'com.google.android.gms'
  You can temporarily disable this error with android.enforceUniquePackageName=false
  However, this is temporary and will be enforced in 1.0

**So** what i did was that i removed the plugin:
https://github.com/floatinghotpot/google-play-services
which got rid of the previous error aka "more than one "com.google.android.gms" package name"

**But** that gave me a new error which was:
                Error Code:
         	2
              Output:
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)

**Lastly** i removed the second plugin aswell which was:
https://github.com/floatinghotpot/cordova-plugin-android-support-v4

I was now able to build without any errors, however it seems like i cant use this plugin and the required plugins for onesignal at the same time therefore i was wondering if there was any solutions for solving this problem.

Help is highly appreciated, thanks alot!

**Comment by jkasten2** [comment]
@matte5031 This plugin already includes google-play-services so you are correct in removing the following from your project.
https://github.com/floatinghotpot/google-play-services

However I don't see android-support-v4 in this plugin so it must be coming from a different one. Can you list all the plugins you are using in your app? Also try a new project with just OneSignal, this plugin, and cordova-plugin-android-support-v4.

**Comment by matte5031** [comment]
@jkasten2 Thanks for the reply, i've done what you suggested and only used theese two plugins, altough the same problems occur, I've edited the answer with more from the build log if it can help solve/identify the problem.

**Comment by jkasten2** [comment]
@matte5031 Are you using Crosswalk in your Intel XDK project? If so what version? If you are using 16  or newer you can omit `cordova-plugin-android-support-v4` as it is included with it.

**Comment by matte5031** [comment]
@jkasten2 Nah i'm not using crosswalk in my original project

**Comment by jkasten2** [comment]
@floatinghotpot Can you point me to the commit that Intel XDK would be using? Or do you know if this plugin includes any part of the Android Support Library v4?

**Comment by matte5031** [comment]
@jkasten2  Yes the version that was commited by Intel was version 5.3.3. I downloaded the latest version 5.3.4 and imported it locally, with a few minor changes like changing dependency id and name of the plugin to fetch its now working, thanks

**Comment by aifabio** [comment]
Can you share the changes you made to work?

**Comment by aifabio** [comment]
Can you share the changes you made to work?
